### ISSUE TITLE
Failure to download videos.

### ISSUE THREAD

**Issue by cgddrd** [charlienewey/panopticlone#4]
**Overview:**

Panopticlone fails to download videos from any Panopto sessions hosted at [http://abercast.aber.ac.uk](http://abercast.aber.ac.uk). 

**From initial debugging and fault testing, this has been traced back to an issue (it is believed) on Panopto's end, where the ```IosVideoUrl``` property is returned containing only an empty string.**

**Environment:**

- Mac OSX 10.11.2
- Google Chrome 47.0.2526.106 (64-bit) (Also tested in Canary 49.0.2593.0 (64-bit))
- Panopticlone 0.3.0

**Steps to Repeat:**

1. Go-to [http://abercast.aber.ac.uk](http://abercast.aber.ac.uk) and login via Blackboard using student credentials.

2. Arrive at [http://abercast.aber.ac.uk/Panopto/Pages/Sessions/List.aspx](http://abercast.aber.ac.uk/Panopto/Pages/Sessions/List.aspx), and select a folder from the bottom-left list. 

3. Arrive at folder (e.g. [http://abercast.aber.ac.uk/Panopto/Pages/Sessions/List.aspx#folderID=%22961d883a-dfcd-4f0a-bb49-e20773c4d5a8%22](http://abercast.aber.ac.uk/Panopto/Pages/Sessions/List.aspx#folderID=%22961d883a-dfcd-4f0a-bb49-e20773c4d5a8%22)) and click the Panopticlone extension button.

4. Panopticlone successfully detects all available sessions, and provides links to download video files:
<img width="494" alt="screen shot 2015-12-16 at 10 37 59" src="https://cloud.githubusercontent.com/assets/2536819/11838794/27125d3e-a3e1-11e5-906e-1cd394179050.png">

5. Following clicking on any of the download links, Panopticlone successfully creates a new notification, **but no download is triggered.**
<img width="373" alt="screen shot 2015-12-16 at 10 40 29" src="https://cloud.githubusercontent.com/assets/2536819/11838856/739c56e6-a3e1-11e5-95da-8cbb6e9a4c3f.png">

**Comment by charlienewey** [comment]
Closed by 82dc3975be21b246da1e8b5954ba6f3d8178dc44! :-)
