### ISSUE TITLE
Videos Downloading Improperly

### ISSUE THREAD

**Issue by ChatBotMatt** [charlienewey/panopticlone#6]
Overview:

Panopticlone fails to correctly download videos from certain modules. 

The videos, when downloaded, contain only what appears to be metadata. 

This has been found for both https://aberystwyth.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID=%22c598c55c-6289-47ea-b7dc-a957009c3d11%22 (Machine Learning 2018-19) and https://aberystwyth.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID=%22eee38cae-c73d-4008-b883-a96500df8cfa%22 (Computational Bioinformatics 2018-19) 
although some other modules (Computer Vision 2018-19 for example) worked properly, and for both individual and bulk downloads.

The only data stored within the bad files is along the lines of 

> #EXTM3U
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=371686,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=1280x720,CLOSED-CAPTIONS=NONE
> 244086/index.m3u8

Notably, on the Machine Learning folder, the WEKA Primer lecture can be downloaded and played normally in either the bulk or the individual download.

Environment:

Windows 10, Version 1809
Google Chrome 74.0.3729.131 (64-bit) (official build)
Panopticlone 0.3.3
Steps to Repeat:

Go-to http://abercast.aber.ac.uk and login via Blackboard using student credentials.
Arrive at https://aberystwyth.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID=%22c598c55c-6289-47ea-b7dc-a957009c3d11%22 and click the Panopticlone extension button.
Panopticlone successfully detects all available sessions, and provides links to download video files.
Following a download, each file is downloaded with only what looks like some metadata (see above), instead of the actual content.

**Comment by charlienewey** [comment]
I no longer have access to AberCast so I'm afraid I can't help you! Contributions welcome, though. :-)
